# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

from pyspark.sql.functions import *

# COMMAND ----------

df_calender = spark.read.format("delta").load("/Volumes/adventure_work/bronze/data/Calendar/")
df_calender = df_calender.withColumn("unix_date",from_unixtime(unix_timestamp('Date', 'M/d/yyy')))
df_calender = df_calender.withColumn("date", to_date("unix_date")).drop("unix_date")
df_calender_clean = df_calender.withColumn("month", month("date"))\
                    .withColumn("year", year("date"))\
                    .drop("ingestion_timestamp")

# COMMAND ----------

df_calender_clean.display()

# COMMAND ----------

df_returns = spark.read.format("delta").load("/Volumes/adventure_work/bronze/data/Sales/Sales*")

# COMMAND ----------

df_returns.display()

# COMMAND ----------


